### ISSUE TITLE
could not find function "asDataFrame" 

### ISSUE THREAD

**Issue by laracp** [omixer/omixer-rpmR#3]
Hi there, 

I went through the example and ran into the following problem with v 0.3.1. 

> coverage <- asDataFrame(mods, "coverage")
Error in asDataFrame(mods, "coverage") : 
  could not find function "asDataFrame"

Installation looked fine and everything went smoothly up until this point. 

Thanks.

**Comment by omixer** [comment]
Hi Lara,

asDataFrame is a function in omixer-rpmR. Could you make sure the library is loaded before you call this function?
If this does not work please send the output of  sessionInfo() and the script or the list of commands you are running before getting this error.

cheers,
Youssef

**Comment by laracp** [comment]
Hi Youssef, 

The library was indeed loaded. I am just running through the usage example you have provided for omixer-rpmR. 

```
library(omixerRpm)
# read a functional profile matrix into R or create it inside R. Please note that row.names should not be used while reading the matrix. 
dat <- read.table("matrix.tsv", header=T, sep="\t")
# Run the module mapping on the loaded table.
mods <- rpm(dat, minimum.coverage=0.3, annotation = 1)

# alternatively run the mapping without loading the table into R.
mods <- rpm("matrix.tsv", minimum.coverage=0.3, annotation = 1)

# Load the default mapping database
db <- loadDefaultDB()
# get the name of the first predicted module
getNames(db, mods@annotation[1,])

# get the abundance|coverage as a data.frame with module id and description
coverage <- asDataFrame(mods, "coverage")
```
 
When the library is loaded I try to search the help for this function but receive the following error:
> ?asDataFrame
No documentation for ‘asDataFrame’ in specified packages and libraries:

Here is the output for sessionInfo()
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] omixerRpm_0.3.1

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3  
```
Many thanks for your help, 
Lara

**Comment by omixer** [comment]
Could you please install this version of the library https://github.com/omixer/omixer-rpmR/releases/tag/0.3.1?
It should fix the problem. I messed up the versioning and indeed in the latest release asDataFrame is not a function.
The link I sent you was labeled as a pre-release and this is why you probably did not install it. 
I hope this helps and if not I will spend more time on Monday to find a solution.

Best,
Youssef

**Comment by laracp** [comment]
Still no luck with the new installation. But Monday sounds great. 

Thanks again for your help. 

Lara

**Comment by omixer** [comment]
Hi Lara, 

Indeed version 0.3.1 does not work. I released version 0.3.2 and tested it in a fresh docker environment to make sure `asDataFrame` is included in the package. This version will solve your problem!

Thank you so much for your feedback and please let me know if you face further issues using the library.

Best,
Youssef

**Comment by laracp** [comment]
Success! Thank you Youssef. 

Best, 
Lara
